### PR TITLE
fix(app): fix CSS to highlight sequence flows

### PR DESCRIPTION
**Pull request by saig0**
* dump bpmn-js version to 6.5.1

### CODE REVIEW

**Comment by ahumellihuk** [comment]
But if you remove `bpmn-js` webjar, where are do you get the CSS resources from for `header.html`?

**Comment by saig0** [comment]
I removed the webjar dep because the dependency to `bpmn-js` was outdated. So, I integrated the JS lib directly.

**Comment by ahumellihuk** [comment]
Sorry for delay. What I meant to say was `header.html` still refers to the removed webjar for CSS resources:
```
    <!-- bpmn-js viewer -->
    <link type="text/css" rel="stylesheet" href="/webjars/bpmn-js/dist/assets/diagram-js.css"/>
    <link type="text/css" rel="stylesheet" href="/webjars/bpmn-js/dist/assets/bpmn-font/css/bpmn-embedded.css"/>
```

**Comment by saig0** [comment]
Ah, true. Good catch :+1:

**Pull request merged**
