### PR TITLE
fix: allow entity.MessageEntity.payload to be larger than 255 chars

### LINKED ISSUE #138: bug: VARCHAR(255) too small for message payload
On version 0.18.0 from docker hub.

When sending a message to the Zeebe broker, if the payload is larger than 255 characters, the monitor throws an exception because the database column is of type `VARCHAR(255)`

Example failing payload.
```
{
    "worker_id":"one",
    "url": "http://www3.septa.org/hackathon/TransitViewAll/",
    "method": "get",
    "period": "R/PT10S"
  }
```
Error:
```
2020-04-29 16:03:24.544 ERROR 1 --- [pool-1-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Value too long for column "PAYLOAD_ VARCHAR(255)": "STRINGDECODE('fields {\n  key: \""period\""\n  value {\n    string_value: \""R/PT10S\""\n  }\n}\nfields {\n  key: \""method\""\n  valu... (308)"; SQL statement:
insert into message (correlation_key_, message_id_, name_, payload_, state_, timestamp_, key_) values (?, ?, ?, ?, ?, ?, ?) [22001-200]
```

### PR DESCRIPTION
**Pull request by shawnsarwar**
closes #138

### CODE REVIEW

**Comment by shawnsarwar** [comment]
I signed the CLA, not sure why it's hung up.

**Comment by saig0** [comment]
Thank you for the contribution :+1:

**Comment by saig0** [comment]
Regarding the CLA check, it seems that the commit is not linked with your Github account:

> Shawn Sarwar seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

Please have a look :)

**Comment by shawnsarwar** [comment]
@saig0 Yep, dumb on my part. Fixed the CLA issue.

**Comment by saig0** [comment]
:tada:

**Pull request merged**
