### PR TITLE
Added column size specification varchar(16000) to exporter SQL schema

### PR DESCRIPTION
**Pull request by huksley**
Self-explanatory. The current version does not allow to load even the simple BPMN files to WORKFLOW table.

### CODE REVIEW

**Comment by Zelldon** [comment]
Hi @huksley ,

thanks for your contribution.

> The current version does not allow to load even the simple BPMN files to WORKFLOW table.

I think we tested it with H2 and it seems to work, but maybe this is true for other databases. What type of database do you use?

What is the reason for `16000` as value?
Maybe it makes sense to use `CLOB` instead of `VARCHAR` what do you think?

Greets
Chris

**Comment by huksley** [comment]
H2 defaults to 255 symbols if not specified. 
Usually BPMN processes are around 16k or less and split into different processes.
Unsure on using CLOB/TEXT because it can change application logic.

**Comment by huksley** [comment]
Hi I am using H2 and I have had an exception when uploading schema from simpe monitor that workflow.resource_ column can`t fit it due to column being 255 bytes.

After recreating table with resource_ varchar(16000) problem was fixed.

**Comment by huksley** [comment]
> What do you mean with "it can change application logic"? You mean in the simple monitor?

CLOB datatype is not universally supported for example in MySQL/MariaDB it is named TEXT

**Comment by Zelldon** [comment]
Ok yes, but VARCHAR is not designed for this type of data (large texts). If the user wants to use another database, then he have to change it, maybe in the future we can also add an mechanism for auto detection.

The `VARCHAR(16000)` will also not work for oracle, since the max length is 4000 characters see here https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1822 or for ms sqlserver it is 8000, see here https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-2017 .

**Comment by huksley** [comment]
Superceeded by https://github.com/zeebe-io/zeebe-simple-monitor/pull/39

**Pull request closed without merging**
