### PR TITLE
feat: optional route prefix

### PR DESCRIPTION
**Pull request by shawnsarwar**
feat: allow all routes in zeebe-simple-monitor to be prefixed, using the optional `server.context-path` directive. The default prefix is `/`, and all prefixes should contain a trailing `/`. EX: `/monitor/`
Changes:
 - Base server path is set by `sever.context-path` setting.
 - Added a Java Config for the configuration of static assets to allow for prefixing.
 - Put `base_path` on the global scope for all JS scripts in the footer template.
 - Changed hard coded path values in all relevent JS and template files to account for a path prefix. I.E. `/views/* -> {{server.context-path}}views/*`

_note: I'm happy to make changes. I don't have much experience with Java outside of Android, so I apologize if anything looks particularly un-idiomatic from a Java / Spring Boot point of view._

### CODE REVIEW

**Comment by saig0** [comment]
@shawnsarwar awesome :tada: 

I'll have a look soon.

**Review by saig0 — CHANGES_REQUESTED** [review]
Finally, I had time to try it out. It worked nicely :+1:  
Just, the web socket notifications don't work anymore. 

Looking at the changes, I see that we can remove the part in the backend. Spring Boot has built-in support for a different context path by setting the property `server.servlet.context-path` (https://www.baeldung.com/spring-boot-context-path). This seems to work well so far. 

So, I think we need only the changes in the HTML templates and the JS. Maybe, we can make it work even if the user forgets the `/` at the end (e.g. `/foo`).

**Comment by shawnsarwar** [comment]
Thanks for taking at look at it @saig0, it's strange that the websockets didn't work for you. Can you tell me where so I can try to replicate it? I'll give `server.servlet.context-path` a go and see if that works without the routing changes, but it might be next week before I have time.

**Comment by saig0** [comment]
Nice :+1: no pressure :)

The web socket is used to send notifications of the workflow instance. If you're in the workflow instance view and the instance changes (e.g. by completing a job) then the backend sends a notification that is shown in an infobox (i.e. "The workflow instance has changed. Reload" or something like this).

**Comment by shawnsarwar** [comment]
hey @saig0, I went back to take a look at this today with the latest changes from upstream, and I'm having a strange issue. The patch doesn't run as-is after merge. Mustasch is no longer able to pick up variables like `server.context-path` which I was using. The patch works normally if I don't take the upgrade from Spring 2.3.2 -> 2.3.3. I don't see anything in the spring patch notes that look related. Any ideas?

**Comment by shawnsarwar** [comment]
I'm not going to have time to take a look at this for a while, so I'm going to close this for now.

**Pull request closed without merging**
