### PR TITLE
feat(app): show active workers

### PR DESCRIPTION
**Pull request by saig0**
* show a list of all worker with name, job type and last poll time

image

### CODE REVIEW

**Comment by Zelldon** [comment]
Nice :+1: maybe we can also show the number of last activated jobs, if makes sense?

**Comment by saig0** [comment]
So you want to see if the worker is busy? I'm not sure what numbers I can show there. Currently, I have only one entry per worker and job type in the database.

**Comment by Zelldon** [comment]
Ok I thought the ACTIVATED Batch record contains the number of activated jobs or? Maybe this?

**Comment by saig0** [comment]
Yes, but there is a new batch every x second. It would be very flaky and shows zero most of the time.

**Comment by Zelldon** [comment]
hm ok :sweat_smile:

**Pull request merged**
